package com.example.application.exception

enum class ErrorCode(
    val code: String,
    val messageKey: String,
    val status: Int
) {

    INVALID_INPUT("COMMON_001", "error.invalid_input", 400),
    INVALID_JSON("COMMON_002", "error.invalid_json", 400),
    INTERNAL_ERROR("COMMON_999", "error.internal_error", 500),
    RESOURCE_NOT_FOUND("RESOURCE_001","error.resource_not_found", 404),
    USER_NOT_FOUND("USER_001", "error.user_not_found", 404),
    USER_ALREADY_EXISTS("USER_002", "error.user_already_exists", 409),
    DUPLICATE_EMAIL("AUTH_003", "error.duplicate_email", 409),
    DUPLICATE_NICKNAME("AUTH_004", "error.duplicate_nickname", 409),
    EMAIL_NOT_VERIFIED("AUTH_005", "error.email_not_verified", 400),
    AUTH_CODE_NOT_FOUND("AUTH_006", "error.auth_code_not_found", 404),
    AUTH_CODE_MISMATCH("AUTH_007", "error.auth_code_mismatch", 400),
    ALREADY_SIGNED_EMAIL("AUTH_008", "error.already_signed_email", 409),
    ALREADY_LOGGED_OUT("AUTH_009", "error.already_logged_out", 400),
    UNREGISTERED_UNIVERSITY("AUTH_010", "error.unregistered_university", 400),
    INVALID_MAJOR_SELECTION("AUTH_011", "error.invalid_major_selection", 400),
    UNAUTHORIZED("AUTH_001", "error.unauthorized", 401),
    FORBIDDEN("AUTH_002", "error.forbidden", 403),
    BOARD_NOT_FOUND("BOARD_001", "error.board_not_found", 404),
    POST_NOT_FOUND("POST_001", "error.post_not_found", 404),
    ANONYMOUS_NOT_ALLOWED("POST_002", "error.anonymous_not_allowed", 400),
    COMMENT_NOT_FOUND("COMMENT_001", "error.comment_not_found", 404),
    POST_LIKE_DUPLICATE("POST_003", "error.post_like_duplicate", 409),
    POST_LIKE_NOT_FOUND("POST_004", "error.post_like_not_found", 404),
    POST_ALREADY_DELETED("POST_005", "error.post_already_deleted", 409),
    COMMENT_DEPTH_NOT_ALLOWED("COMMENT_002", "error.comment_depth_not_allowed", 400),
    INVALID_COMMENT_PARENT("COMMENT_003", "error.invalid_comment_parent", 400),
    TIMETABLE_NOT_FOUND("TIMETABLE_001", "error.timetable_not_found", 404),
    TIMETABLE_LECTURE_DUPLICATE("TIMETABLE_002", "error.timetable_lecture_duplicate", 409),
    LECTURE_NOT_IN_MEMBER_UNIVERSITY("TIMETABLE_003", "error.lecture_not_in_member_university", 400),
    LECTURE_NOT_IN_SEMESTER("TIMETABLE_004", "error.lecture_not_in_semester", 400),
    TIMETABLE_LECTURE_NOT_FOUND("TIMETABLE_005", "error.timetable_lecture_not_found", 404),
    TIMETABLE_LECTURE_CONFLICT("TIMETABLE_006", "error.timetable_lecture_conflict", 409),
    COURSE_NOT_FOUND("COURSE_001", "error.course_not_found", 404),
    COURSE_REVIEW_NOT_FOUND("COURSE_002", "error.course_review_not_found", 404),
    COURSE_REVIEW_ALREADY_EXISTS("COURSE_003", "error.course_review_already_exists", 409),
    LECTURE_NOT_IN_COURSE("COURSE_004", "error.lecture_not_in_course", 400)
}
